env:
  version: v3.21

name: Alpine ISO Builder

on:
  push:

jobs:
  build_ISOs:
    runs-on: ubuntu-24.04
    container:
      image: alpine:3.21

    steps:
      - name: Install software
        run: |
          apk update
          apk upgrade
          apk --no-cache add alpine-sdk build-base apk-tools alpine-conf \
              busybox fakeroot syslinux xorriso squashfs-tools sudo mtools \
              dosfstools grub-efi

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download aports
        run: git clone --depth=1 https://gitlab.alpinelinux.org/alpine/aports.git

      - name: Configure build keys
        run: echo | abuild-keygen -i -a

      - name: Make ISO (${{ env.version }})
        run: |
          chmod +x *.sh
          mv *.sh aports/scripts/
          cd aports/scripts/

          ./mkimage.sh \
              --tag ${version} \
              --arch x86_64 \
              --profile docker \
              --outdir ../../ \
              --repository https://dl-cdn.alpinelinux.org/alpine/${version}/main \
              --repository https://dl-cdn.alpinelinux.org/alpine/${version}/community

      - name: Upload files
        uses: actions/upload-artifact@v4
        with:
          name: files
          path: .
          include-hidden-files: true

  release_ISOs:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-24.04
    needs: build_ISOs
    steps:
      - name: Download files
        uses: actions/download-artifact@v4
        with:
          name: files

      - name: Release AlpDock ISO
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          echo -e "Changelog\n---------" > changelog.txt
          git log --reverse --pretty=format:"- %h: %s" $(git describe --tags --abbrev=0 HEAD^)..HEAD | egrep -v 'fix:|minor:|typo:' >> changelog.txt

          gh release create ${{ github.ref_name }} \
            --verify-tag \
            --latest \
            --notes-file changelog.txt \
            *.iso
