env:
  version: v3.20

name: Alpine ISO Builder

on:
  push:
    tags:
    - 'v*'

jobs:
  build_ISOs:
    runs-on: ubuntu-22.04
    container:
      image: alpine:3.20

    steps:
      - uses: actions/checkout@v4

      - name: Install software
        run: |
          apk update
          apk upgrade
          apk --no-cache add alpine-sdk build-base apk-tools alpine-conf \
              busybox fakeroot syslinux xorriso squashfs-tools sudo mtools \
              dosfstools grub-efi

      - name: Download aports
        run: git clone --depth=1 https://gitlab.alpinelinux.org/alpine/aports.git

      - name: Configure build keys
        run: echo | abuild-keygen -i -a

      - name: Make ISO (${{ env.version }})
        run: |
          chmod +x *.sh
          mv *.sh aports/scripts/
          cd aports/scripts/

          ./mkimage.sh \
              --tag ${version} \
              --arch x86_64 \
              --profile docker \
              --outdir ../../ \
              --repository https://dl-cdn.alpinelinux.org/alpine/${version}/main \
              --repository https://dl-cdn.alpinelinux.org/alpine/${version}/community

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            *.iso
